### ISSUE TITLE
Code bugs on running ppflow and potential checkpoints sharing 

### ISSUE THREAD

**Issue by lalalalala-ai** [EDAPINENUT/ppflow#1]
Dear author,

I have recently read your great work and try to play with it. Unfortunately,  the code gave the error like below. Interesting thing, I have no problems to run "python train_diffpp.py" using exactly the same environment. Also,  I wonder whether you would be okay to share your trained checkpoint file ?  It would be very convenient for some people like me to try it out without training everything from scratch.    Your help is greatly appreciated.

Kind regards,

NFO: Using pytorch backend
[2024-08-12 21:20:03,448::train::INFO] Namespace(config='./configs/train/ppflow.yml', debug=False, device='cuda', finetune=None, logdir='./logs', num_workers=4, resume=None, tag='')
INFO: Namespace(config='./configs/train/ppflow.yml', debug=False, device='cuda', finetune=None, logdir='./logs', num_workers=4, resume=None, tag='')
[2024-08-12 21:20:03,451::train::INFO] {'model': {'type': 'ppflow', 'res_feat_dim': 128, 'pair_feat_dim': 64, 'flow': {'eps_net_opt': {'num_layers': 6}}, 'train_structure': True, 'train_sequence': True}, 'train': {'loss_weights': {'rot': 1.0, 'pos': 1.0, 'seq': 1.0, 'dihed': 1.0}, 'max_iters': 1000000, 'val_freq': 1000, 'batch_size': 4, 'seed': 2022, 'max_grad_norm': 100.0, 'optimizer': {'type': 'adam', 'lr': 5e-05, 'weight_decay': 0.0, 'beta1': 0.9, 'beta2': 0.999}, 'scheduler': {'type': 'plateau', 'factor': 0.8, 'patience': 10, 'min_lr': 1e-06}}, 'dataset': {'type': 'pair', 'data_dir': './dataset/ppbench2024/', 'split_path': './data/processed/[split.pt](http://split.pt/)', 'processed_dir': './data/processed/', 'include_pdb_path': './data/[pdb_filtered2.pt](http://pdb_filtered2.pt/)', 'exclude_pdb_path': './data/[pdb_benchmark.pt](http://pdb_benchmark.pt/)', 'transform': [{'type': 'mask_peptide', 'mask_type': True, 'mask_pos': True}, {'type': 'fix_patch', 'patch_target': 'receptor', 'anchor_target': 'peptide', 'anchor_flag': 'mask_gen_pos', 'patch_size': 128, 'contin_chain': False}, {'type': 'merge_chains'}, {'type': 'center_pos', 'center_flag': 'receptor_flag'}]}, 'config': './configs/train/ppflow.yml', 'logdir': './logs', 'debug': False, 'device': 'cuda', 'num_workers': 4, 'tag': '', 'resume': None, 'finetune': None}
INFO: {'model': {'type': 'ppflow', 'res_feat_dim': 128, 'pair_feat_dim': 64, 'flow': {'eps_net_opt': {'num_layers': 6}}, 'train_structure': True, 'train_sequence': True}, 'train': {'loss_weights': {'rot': 1.0, 'pos': 1.0, 'seq': 1.0, 'dihed': 1.0}, 'max_iters': 1000000, 'val_freq': 1000, 'batch_size': 4, 'seed': 2022, 'max_grad_norm': 100.0, 'optimizer': {'type': 'adam', 'lr': 5e-05, 'weight_decay': 0.0, 'beta1': 0.9, 'beta2': 0.999}, 'scheduler': {'type': 'plateau', 'factor': 0.8, 'patience': 10, 'min_lr': 1e-06}}, 'dataset': {'type': 'pair', 'data_dir': './dataset/ppbench2024/', 'split_path': './data/processed/[split.pt](http://split.pt/)', 'processed_dir': './data/processed/', 'include_pdb_path': './data/[pdb_filtered2.pt](http://pdb_filtered2.pt/)', 'exclude_pdb_path': './data/[pdb_benchmark.pt](http://pdb_benchmark.pt/)', 'transform': [{'type': 'mask_peptide', 'mask_type': True, 'mask_pos': True}, {'type': 'fix_patch', 'patch_target': 'receptor', 'anchor_target': 'peptide', 'anchor_flag': 'mask_gen_pos', 'patch_size': 128, 'contin_chain': False}, {'type': 'merge_chains'}, {'type': 'center_pos', 'center_flag': 'receptor_flag'}]}, 'config': './configs/train/ppflow.yml', 'logdir': './logs', 'debug': False, 'device': 'cuda', 'num_workers': 4, 'tag': '', 'resume': None, 'finetune': None}
[2024-08-12 21:20:03,452::train::INFO] Loading dataset...
INFO: Loading dataset...
[2024-08-12 21:22:07,327::train::INFO] Train 13534 | Val 1906
INFO: Train 13534 | Val 1906
[2024-08-12 21:22:07,380::train::INFO] Building model...
INFO: Building model...
[2024-08-12 21:22:20,888::train::INFO] Number of parameters: 4033673
INFO: Number of parameters: 4033673
Loading Structures for train set...
Loading Structures for val set...
Traceback (most recent call last):
  File "train_ppf.py", line 169, in <module>
    train(it)
  File "train_ppf.py", line 103, in train
    loss_dict = model(batch)
  File "/home/projects/def-pmkim/anaconda3/envs/proteinsgm2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/lustre04/scratch/pre3/pre2/pre/ppflow_contral_group/ppflow/ppflow/models/ppflow.py", line 105, in forward
    loss_dict = self.flow(
  File "/home/projects/def-pmkim/anaconda3/envs/proteinsgm2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/lustre04/scratch/pre3/pre2/pre/ppflow_contral_group/ppflow/ppflow/modules/flows/torusflow.py", line 162, in forward
    ur_t, r_t = self.rot_sampler.sample_field(R_1, t)
  File "/lustre04/scratch/pre3/pre2/pre/ppflow_contral_group/ppflow/ppflow/modules/flows/flow_sampler.py", line 42, in sample_field
    t, ut, xt = self.basic_sampler.sample_location_and_conditional_flow(x0, x1, time_der=True, t=t)
  File "/lustre04/scratch/pre3/pre2/pre/ppflow_contral_group/ppflow/ppflow/modules/flows/flow_sampler.py", line 454, in sample_location_and_conditional_flow
    xt = self.sample_xt(x0, x1, t, if_matrix_format=True)
  File "/lustre04/scratch/pre3/pre2/pre/ppflow_contral_group/ppflow/ppflow/modules/flows/flow_sampler.py", line 390, in sample_xt
    log_x1, rot_x0 = self.vec_log_map(x0, x1, if_matrix_format=if_matrix_format)
  File "/lustre04/scratch/pre3/pre2/pre/ppflow_contral_group/ppflow/ppflow/modules/flows/flow_sampler.py", line 382, in vec_log_map
    log_x1 = self.vec_manifold.log_not_from_identity(rot_x1, rot_x0)
  File "/home/projects/def-pmkim/anaconda3/envs/proteinsgm2/lib/python3.8/site-packages/geomstats/geometry/lie_group.py", line 508, in log_not_from_identity
    tangent_translation = self.tangent_translation_map(
  File "/home/projects/def-pmkim/anaconda3/envs/proteinsgm2/lib/python3.8/site-packages/geomstats/geometry/lie_group.py", line 397, in tangent_translation_map
    jacobian = self.jacobian_translation(point, left)
  File "/home/projects/def-pmkim/anaconda3/envs/proteinsgm2/lib/python3.8/site-packages/geomstats/geometry/special_orthogonal.py", line 1579, in jacobian_translation
    point = self.regularize(point)
  File "/home/projects/def-pmkim/anaconda3/envs/proteinsgm2/lib/python3.8/site-packages/geomstats/geometry/special_orthogonal.py", line 813, in regularize
    theta_eps = gs.where(gs.isclose(theta, 0.0), 1.0, theta)
  File "/home/projects/def-pmkim/anaconda3/envs/proteinsgm2/lib/python3.8/site-packages/geomstats/_backend/pytorch/__init__.py", line 487, in where
    return _torch.where(condition, x, y)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by EDAPINENUT** [comment]
It mostly because of the incompatibility of geomstats with the newest PyTorch. The geomstats can hardly support torch 2.0+. In this way, we recommend you can use the requirements.txt file to build the environment. Or you can also follow the FoldFlow's installation, as https://github.com/DreamFold/FoldFlow/blob/main/requirements.txt.

**Comment by lalalalala-ai** [comment]
Actually, I am using Torch 1.12 (with cuda 11.3).  Also, would it be possible to share the checkpoints you already trained? I think try direct sampling might be easier. thx again for your help. I am really apprecaited

**Comment by lalalalala-ai** [comment]
in case it is useful. I am using geomstats version  2.7.0

**Comment by EDAPINENUT** [comment]
The pre-trained one will be uploaded this month.  Besides, the training is quite fast and cost about only 7 days.
